/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Day = IDL.Record({
  'description' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'activity' : IDL.Text,
});
export const DayProgress = IDL.Record({
  'completed' : IDL.Bool,
  'dayNumber' : IDL.Nat,
});
export const DailyProgress = IDL.Record({ 'completedDays' : IDL.Vec(IDL.Nat) });
export const Program = IDL.Record({
  'title' : IDL.Text,
  'days' : IDL.Vec(Day),
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDay' : IDL.Func([IDL.Nat], [Day], ['query']),
  'getDayProgress' : IDL.Func([IDL.Nat], [DayProgress], ['query']),
  'getDaysRange' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Day)], ['query']),
  'getMyProgress' : IDL.Func([], [DailyProgress], ['query']),
  'getProgram' : IDL.Func([], [Program], ['query']),
  'getProgramStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalDays' : IDL.Nat,
          'completedCount' : IDL.Nat,
          'remainingCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDayComplete' : IDL.Func([IDL.Nat], [], []),
  'resetMyProgress' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Day = IDL.Record({
    'description' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'activity' : IDL.Text,
  });
  const DayProgress = IDL.Record({
    'completed' : IDL.Bool,
    'dayNumber' : IDL.Nat,
  });
  const DailyProgress = IDL.Record({ 'completedDays' : IDL.Vec(IDL.Nat) });
  const Program = IDL.Record({
    'title' : IDL.Text,
    'days' : IDL.Vec(Day),
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDay' : IDL.Func([IDL.Nat], [Day], ['query']),
    'getDayProgress' : IDL.Func([IDL.Nat], [DayProgress], ['query']),
    'getDaysRange' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Day)], ['query']),
    'getMyProgress' : IDL.Func([], [DailyProgress], ['query']),
    'getProgram' : IDL.Func([], [Program], ['query']),
    'getProgramStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalDays' : IDL.Nat,
            'completedCount' : IDL.Nat,
            'remainingCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDayComplete' : IDL.Func([IDL.Nat], [], []),
    'resetMyProgress' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };