/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyProgress { 'completedDays' : Array<bigint> }
export interface Day {
  'description' : string,
  'dayNumber' : bigint,
  'activity' : string,
}
export interface DayProgress { 'completed' : boolean, 'dayNumber' : bigint }
export interface Program {
  'title' : string,
  'days' : Array<Day>,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDay' : ActorMethod<[bigint], Day>,
  'getDayProgress' : ActorMethod<[bigint], DayProgress>,
  'getDaysRange' : ActorMethod<[bigint, bigint], Array<Day>>,
  'getMyProgress' : ActorMethod<[], DailyProgress>,
  'getProgram' : ActorMethod<[], Program>,
  'getProgramStats' : ActorMethod<
    [],
    {
      'totalDays' : bigint,
      'completedCount' : bigint,
      'remainingCount' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDayComplete' : ActorMethod<[bigint], undefined>,
  'resetMyProgress' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];